'use client';

import React from 'react';
import {
  ShieldCheck,
  Zap,
  Globe,
  Video,
  ExternalLink,
  Download,
  AlertOctagon,
  RefreshCw,
  CheckCircle2,
} from 'lucide-react';
import { QAReport } from '../types';

interface QualityScorecardProps {
  report: QAReport;
  onReset?: () => void;
}

export const QualityScorecard: React.FC<QualityScorecardProps> = ({ report, onReset }) => {
  const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

  const getScoreBadge = (score: string) => {
    if (score.startsWith('A'))
      return {
        label: 'EXCELLENT',
        bg: 'bg-emerald-950/60 text-emerald-300 border-emerald-500',
        ring: 'ring-emerald-500/20',
        desc: 'Production ready with minimal issues',
      };
    if (score.startsWith('B'))
      return {
        label: 'GOOD (HEALTHY)',
        bg: 'bg-cyan-950/60 text-cyan-300 border-cyan-500',
        ring: 'ring-cyan-500/20',
        desc: 'Healthy website with minor external asset notices',
      };
    if (score.startsWith('C'))
      return {
        label: 'NEEDS ATTENTION',
        bg: 'bg-amber-950/60 text-amber-300 border-amber-600',
        ring: 'ring-amber-500/20',
        desc: 'Multiple user-facing issues found',
      };
    return {
      label: 'CRITICAL ATTENTION',
      bg: 'bg-rose-950/60 text-rose-300 border-rose-700',
      ring: 'ring-rose-500/20',
      desc: 'Server crashes or breaking exceptions caught',
    };
  };

  const badgeInfo = getScoreBadge(report.quality_score);
  const recordingUrl = report.session_recording_url?.startsWith('http')
    ? report.session_recording_url
    : `${API_BASE}${report.session_recording_url}`;

  const handleDownloadFullReport = () => {
    const reportMd = `# 🛡️ BugScout QA Audit Report: ${report.target_url}\n\n**Overall Quality Grade**: ${report.quality_score} (${report.health_percentage}% Health Score)\n**Audit Date**: ${new Date(report.created_at).toLocaleString()}\n**Test Scope**: ${report.test_scope}\n\n---\n\n## 📊 Executive Summary\n${report.summary}\n\n## 📈 Key Metrics\n- **Pages Visited**: ${report.total_pages_visited}\n- **Network Requests Analyzed**: ${report.total_requests_analyzed}\n- **Total Bugs Discovered**: ${report.bugs.length}\n- **Solari MicroVM Verified Suites**: ${report.sandbox_verified_count}\n\n---\n\n## 🚨 Discovered Bugs & Reproduction Suites\n\n${report.bugs.map((b, idx) => `### ${idx + 1}. [${b.severity.toUpperCase()}] ${b.title}\n- **Category**: ${b.category}\n- **URL**: ${b.url}\n- **Verified in Sandbox**: ${b.verified_in_sandbox ? 'Yes' : 'No'}\n- **Description**: ${b.description}\n\n**Reproduction Steps**:\n${b.repro_steps.map((s, i) => `  ${i + 1}. ${s}`).join('\n')}\n\n**Playwright TypeScript Spec**:\n\`\`\`typescript\n${b.playwright_ts_code || '// N/A'}\n\`\`\`\n`).join('\n---\n\n')}\n\n---\n*Generated by BugScout AI powered by Solari Cloud Infrastructure (https://getsolari.com)*`;

    const blob = new Blob([reportMd], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bugscout_qa_report_${report.session_id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="solari-panel rounded-2xl p-6 sm:p-8 shadow-2xl space-y-6 relative overflow-hidden border border-[#222222]">
      {/* Top Banner with Grade */}
      <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6 pb-6 border-b border-[#1c1c1c]">
        {/* Left Grade and Summary */}
        <div className="flex items-center gap-5">
          <div
            className={`w-20 h-20 rounded-2xl bg-[#080808] ${badgeInfo.bg} flex flex-col items-center justify-center border-2 shadow-2xl shrink-0 font-mono-code ring-4 ${badgeInfo.ring}`}
          >
            <span className="text-3xl font-black">{report.quality_score}</span>
            <span className="text-[9px] font-bold uppercase tracking-wider text-center px-1">
              {badgeInfo.label}
            </span>
          </div>

          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-base sm:text-lg font-bold text-white font-mono-code uppercase tracking-wider">
                Overall Website Health: {report.health_percentage}%
              </h2>
              <span className="text-[10px] font-mono-code px-2.5 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-bold flex items-center gap-1">
                <CheckCircle2 className="w-3 h-3" /> Audit Finished
              </span>
            </div>
            <p className="text-xs text-[#aaaaaa] mt-1 max-w-xl leading-relaxed">{report.summary}</p>
          </div>
        </div>

        {/* Right Actions */}
        <div className="flex flex-wrap items-center gap-3 shrink-0">
          {onReset && (
            <button
              onClick={onReset}
              className="px-4 py-2.5 rounded-xl bg-[#111111] hover:bg-[#1c1c1c] text-white text-xs font-bold font-mono-code flex items-center gap-2 border border-[#262626] transition-all cursor-pointer shadow-md"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              <span>Test Another URL</span>
            </button>
          )}

          <button
            onClick={handleDownloadFullReport}
            className="px-4 py-2.5 rounded-xl bg-[#ffffff] hover:bg-[#eaeaea] text-black text-xs font-bold font-mono-code flex items-center gap-2 transition-all cursor-pointer shadow-lg shadow-white/10"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download Report</span>
          </button>

          {report.session_recording_url && (
            <a
              href={recordingUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="px-4 py-2.5 rounded-xl bg-[#141414] hover:bg-[#202020] text-white text-xs font-bold font-mono-code flex items-center gap-2 border border-[#333333] transition-all shadow-md"
            >
              <Video className="w-3.5 h-3.5 text-cyan-400" />
              <span>Solari Replay Info</span>
              <ExternalLink className="w-3.5 h-3.5 text-[#888888]" />
            </a>
          )}
        </div>
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3.5">
        <div className="p-4 rounded-xl bg-[#0a0a0a] border border-[#1a1a1a]">
          <div className="flex items-center gap-2 text-[#777777] text-xs font-mono-code mb-1">
            <Globe className="w-3.5 h-3.5 text-[#aaaaaa]" />
            <span>Pages Visited</span>
          </div>
          <div className="text-2xl font-bold text-white font-mono-code">
            {report.total_pages_visited}
          </div>
          <p className="text-[10px] text-[#666666] mt-0.5">Navigated live by AI</p>
        </div>

        <div className="p-4 rounded-xl bg-[#0a0a0a] border border-[#1a1a1a]">
          <div className="flex items-center gap-2 text-[#777777] text-xs font-mono-code mb-1">
            <ShieldCheck className="w-3.5 h-3.5 text-[#aaaaaa]" />
            <span>Requests Inspected</span>
          </div>
          <div className="text-2xl font-bold text-white font-mono-code">
            {report.total_requests_analyzed}
          </div>
          <p className="text-[10px] text-[#666666] mt-0.5">APIs, assets & console</p>
        </div>

        <div className="p-4 rounded-xl bg-[#0a0a0a] border border-[#1a1a1a]">
          <div className="flex items-center gap-2 text-[#777777] text-xs font-mono-code mb-1">
            <AlertOctagon className={`w-3.5 h-3.5 ${report.bugs.length > 0 ? 'text-amber-400' : 'text-emerald-400'}`} />
            <span>Notices / Issues</span>
          </div>
          <div className={`text-2xl font-bold font-mono-code ${report.bugs.length > 0 ? 'text-amber-400' : 'text-emerald-400'}`}>
            {report.bugs.length}
          </div>
          <p className="text-[10px] text-[#666666] mt-0.5">Trapped with repro steps</p>
        </div>

        <div className="p-4 rounded-xl bg-[#0a0a0a] border border-[#1a1a1a]">
          <div className="flex items-center gap-2 text-[#777777] text-xs font-mono-code mb-1">
            <Zap className="w-3.5 h-3.5 text-emerald-400" />
            <span>MicroVM Verified</span>
          </div>
          <div className="text-2xl font-bold text-emerald-400 font-mono-code">
            {report.sandbox_verified_count}/{report.bugs.length}
          </div>
          <p className="text-[10px] text-[#666666] mt-0.5">100% reproducible tests</p>
        </div>
      </div>
    </div>
  );
};
