'use client';

import React from 'react';
import {
  ShieldCheck,
  Zap,
  Globe,
  Video,
  ExternalLink,
  Download,
  AlertOctagon,
} from 'lucide-react';
import { QAReport } from '../types';

interface QualityScorecardProps {
  report: QAReport;
}

export const QualityScorecard: React.FC<QualityScorecardProps> = ({ report }) => {
  const getScoreBadge = (score: string) => {
    if (score.startsWith('A')) return 'bg-emerald-950/40 text-emerald-400 border-emerald-800';
    if (score.startsWith('B')) return 'bg-cyan-950/40 text-cyan-400 border-cyan-800';
    if (score.startsWith('C')) return 'bg-amber-950/40 text-amber-400 border-amber-800';
    return 'bg-rose-950/40 text-rose-400 border-rose-800';
  };

  const handleDownloadFullReport = () => {
    const reportMd = `# 🛡️ BugScout QA Audit Report: ${report.target_url}\n\n**Overall Quality Grade**: ${report.quality_score} (${report.health_percentage}% Health Score)\n**Audit Date**: ${new Date(report.created_at).toLocaleString()}\n**Test Scope**: ${report.test_scope}\n\n---\n\n## 📊 Executive Summary\n${report.summary}\n\n## 📈 Key Metrics\n- **Pages Visited**: ${report.total_pages_visited}\n- **Network Requests Analyzed**: ${report.total_requests_analyzed}\n- **Total Bugs Discovered**: ${report.bugs.length}\n- **Solari MicroVM Verified Suites**: ${report.sandbox_verified_count}\n\n---\n\n## 🚨 Discovered Bugs & Reproduction Suites\n\n${report.bugs.map((b, idx) => `### ${idx + 1}. [${b.severity.toUpperCase()}] ${b.title}\n- **Category**: ${b.category}\n- **URL**: ${b.url}\n- **Verified in Sandbox**: ${b.verified_in_sandbox ? 'Yes' : 'No'}\n- **Description**: ${b.description}\n\n**Reproduction Steps**:\n${b.repro_steps.map((s, i) => `  ${i + 1}. ${s}`).join('\n')}\n\n**Playwright TypeScript Spec**:\n\`\`\`typescript\n${b.playwright_ts_code || '// N/A'}\n\`\`\`\n`).join('\n---\n\n')}\n\n---\n*Generated by BugScout AI powered by Solari Cloud Infrastructure (https://getsolari.com)*`;

    const blob = new Blob([reportMd], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bugscout_qa_report_${report.session_id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="solari-panel rounded-xl p-5 sm:p-6 shadow-xl space-y-5 relative overflow-hidden">
      <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-5 pb-5 border-b border-[#1c1c1c]">
        {/* Left Score Summary */}
        <div className="flex items-center gap-4">
          <div
            className={`w-14 h-14 rounded-lg bg-[#0a0a0a] ${getScoreBadge(
              report.quality_score
            )} flex flex-col items-center justify-center border shrink-0 font-mono-code`}
          >
            <span className="text-xl font-bold">{report.quality_score}</span>
            <span className="text-[9px] uppercase tracking-wider opacity-70">Grade</span>
          </div>

          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-semibold text-white font-mono-code uppercase tracking-wider">
                QA Audit Scorecard
              </h2>
              <span className="text-[10px] font-mono-code px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-semibold">
                Completed
              </span>
            </div>
            <p className="text-xs text-[#888888] mt-1 max-w-xl leading-relaxed">{report.summary}</p>
          </div>
        </div>

        {/* Right Actions */}
        <div className="flex flex-wrap items-center gap-2.5 shrink-0">
          <button
            onClick={handleDownloadFullReport}
            className="px-3 py-1.5 rounded-lg bg-[#0e0e0e] hover:bg-[#181818] text-[#cccccc] text-xs font-mono-code flex items-center gap-1.5 border border-[#222222] transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5 text-white" />
            <span>Download Report (.md)</span>
          </button>

          {report.session_recording_url && (
            <a
              href={report.session_recording_url}
              target="_blank"
              rel="noopener noreferrer"
              className="px-3 py-1.5 rounded-lg bg-rose-950/30 hover:bg-rose-950/50 text-rose-200 text-xs font-mono-code flex items-center gap-1.5 border border-rose-900/40 transition-all"
            >
              <Video className="w-3.5 h-3.5 text-rose-400" />
              <span>Session Replay</span>
              <ExternalLink className="w-3 h-3" />
            </a>
          )}
        </div>
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="p-3 rounded-lg bg-[#0a0a0a] border border-[#1a1a1a]">
          <div className="flex items-center gap-1.5 text-[#666666] text-[11px] font-mono-code mb-0.5">
            <Globe className="w-3 h-3 text-[#888888]" />
            <span>Pages Visited</span>
          </div>
          <div className="text-xl font-bold text-white font-mono-code">
            {report.total_pages_visited}
          </div>
        </div>

        <div className="p-3 rounded-lg bg-[#0a0a0a] border border-[#1a1a1a]">
          <div className="flex items-center gap-1.5 text-[#666666] text-[11px] font-mono-code mb-0.5">
            <ShieldCheck className="w-3 h-3 text-[#888888]" />
            <span>Requests Analyzed</span>
          </div>
          <div className="text-xl font-bold text-white font-mono-code">
            {report.total_requests_analyzed}
          </div>
        </div>

        <div className="p-3 rounded-lg bg-[#0a0a0a] border border-[#1a1a1a]">
          <div className="flex items-center gap-1.5 text-[#666666] text-[11px] font-mono-code mb-0.5">
            <AlertOctagon className="w-3 h-3 text-rose-400" />
            <span>Trapped Anomalies</span>
          </div>
          <div className="text-xl font-bold text-rose-400 font-mono-code">{report.bugs.length}</div>
        </div>

        <div className="p-3 rounded-lg bg-[#0a0a0a] border border-[#1a1a1a]">
          <div className="flex items-center gap-1.5 text-[#666666] text-[11px] font-mono-code mb-0.5">
            <Zap className="w-3 h-3 text-emerald-400" />
            <span>MicroVM Verified</span>
          </div>
          <div className="text-xl font-bold text-emerald-400 font-mono-code">
            {report.sandbox_verified_count}/{report.bugs.length}
          </div>
        </div>
      </div>
    </div>
  );
};
